### ISSUE TITLE
pandasai :  from where reader.run_pandas_ai come from ? An error occurs when  call this function

### ISSUE THREAD

**Issue by PonceOrtiz** [emptycrown/llama-hub#238]
I´m running the examples for pandasai , but when executes this code an error raise

response =reader.run_pandas_ai(
    df, 
    "Which are the 5 happiest countries?", 
    is_conversational_answer=False
)

Error :
response =reader.run_pandas_ai(
NameError: name 'reader' is not defined

Library declaration : 
from llama_index import download_loader
from pandasai.llm.openai import OpenAI
import pandas as pd

**Comment by EmanuelCampos** [comment]
There's an error on the readme, you need to rename the variable `loader` to `reader`:

```md
# set is_conversational_answer=False to get parsed output
loader = PandasAIReader(llm=llm)
response = reader.run_pandas_ai(
    df, 
    "Which are the 5 happiest countries?", 
    is_conversational_answer=False
)
print(response)
```

After this you'll have other errors since pandasai had a few breaking changes, so we need to update the loader to be updated with them. or figure out which was the latest version working with us and use it, if still working, will try to take a look at it soon.

Closing this issue for now, feel free to open a PR with a contribution to fix this!
