### ISSUE TITLE
Does not load PDFs.

### ISSUE THREAD

**Issue by dahifi** [emptycrown/llama-hub#24]
I saw from the readme that this loader will call the MP3 loader, and immediately tested whether it could do the same with a PDF. 

Didn't work, will dig in whether that functionality is here or on the downstream loaders.

**Comment by emptycrown** [comment]
Which loader are you referring to in particular?

**Comment by emptycrown** [comment]
@dahifi there was an unrelated bug with SimpleDirectoryReader earlier today that is not fixed. I think your issue is resolved but feel free to open another issue if not. I just tried this code and it's working:
```
from gpt_index import download_loader

RemoteReader = download_loader("RemoteReader")

loader = RemoteReader()
documents = loader.load_data(url="https://arxiv.org/pdf/2211.05110.pdf")
```

If you're running locally, make sure to clear the `.modules` directory so that the updated loader is used.

**Comment by dahifi** [comment]
Thanks, I'll try this. There's a new lib called Unstructured that I'm looking at as well. The pypdf module by itself didn't give me great results by itself, might need some llm chains to clean up some of the formatting. Thx for getting back.
